/*
 * Copyright (C) 2013 Jon
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package net.jonathansmith.javadpad.client.threads.runtimeselect.gui.toolbar;

import javax.swing.JPanel;

/**
 *
 * @author Jon
 */
public class RuntimeSelectToolbar extends JPanel {

    /**
     * Creates new form ClientMainToolbar
     */
    public RuntimeSelectToolbar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setUser = new javax.swing.JButton();
        setExperiment = new javax.swing.JButton();
        setData = new javax.swing.JButton();
        addPlugin = new javax.swing.JButton();
        shutdown = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(120, 32767));
        setMinimumSize(new java.awt.Dimension(120, 0));
        setPreferredSize(new java.awt.Dimension(120, 300));

        setUser.setText("Set User");
        setUser.setToolTipText("Set the current user, either by creating or loading one in the datase");
        setUser.setBorder(null);
        setUser.setMargin(new java.awt.Insets(2, 8, 2, 8));
        setUser.setMaximumSize(new java.awt.Dimension(105, 23));
        setUser.setMinimumSize(new java.awt.Dimension(105, 23));
        setUser.setPreferredSize(new java.awt.Dimension(105, 23));

        setExperiment.setText("Set Experiment");
        setExperiment.setToolTipText("Create a new experiment");
        setExperiment.setBorder(null);
        setExperiment.setMargin(new java.awt.Insets(2, 8, 2, 8));
        setExperiment.setMaximumSize(new java.awt.Dimension(105, 23));
        setExperiment.setMinimumSize(new java.awt.Dimension(105, 23));
        setExperiment.setPreferredSize(new java.awt.Dimension(105, 23));

        setData.setText("Data");

        addPlugin.setText("Add Plugin");

        shutdown.setText("Shutdown");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setUser, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(setExperiment, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(setData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addPlugin, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shutdown, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addPlugin, setData, setExperiment, setUser, shutdown});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(setUser, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(setExperiment, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(setData)
                .addGap(5, 5, 5)
                .addComponent(addPlugin)
                .addGap(5, 5, 5)
                .addComponent(shutdown)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addPlugin, setData, setExperiment, setUser, shutdown});

    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addPlugin;
    public javax.swing.JButton setData;
    public javax.swing.JButton setExperiment;
    public javax.swing.JButton setUser;
    public javax.swing.JButton shutdown;
    // End of variables declaration//GEN-END:variables
}
