/*
 * Copyright (C) 2013 Jon
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package net.jonathansmith.javadpad.client.threads.data.overview.pane;

import java.awt.Color;
import java.awt.Component;

import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

import net.jonathansmith.javadpad.client.gui.displayoptions.pane.CurrentRecordPane;
import net.jonathansmith.javadpad.common.database.Record;
import net.jonathansmith.javadpad.common.database.records.Experiment;

/**
 *
 * @author Jon
 */
public class DataPane extends CurrentRecordPane {

    /**
     * Creates new form ClientMainPane
     */
    public DataPane() {
        initComponents();
    }
    
    @Override
    public void setCurrentData(Record record) {
        // TODO: Display based on current data type?
        if (record instanceof Experiment) {
            Experiment exp = (Experiment) record;
            this.experimentName.setText(exp.getName());
            this.experimentDescription.setText(exp.getDescription());
            this.numberOfLoaded.setText(String.valueOf(exp.getLoadedData().size()));
            this.numberOfAnalysed.setText(String.valueOf(exp.getAnalyserData().size()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        experimentName = new JTextField();
        jScrollPane1 = new JScrollPane();
        experimentDescription = new JTextArea();
        experimentDescription1 = new JLabel();
        numberOfAnalysed = new JTextField();
        experimentDescription2 = new JLabel();
        numberOfLoaded = new JTextField();

        jLabel1.setText("Experiment Name:");

        jLabel2.setText("Experiment Description:");

        experimentName.setEditable(false);
        experimentName.setBackground(new Color(255, 255, 255));

        experimentDescription.setColumns(20);
        experimentDescription.setRows(5);
        jScrollPane1.setViewportView(experimentDescription);

        experimentDescription1.setText("Loaded Datasets:");

        numberOfAnalysed.setEditable(false);
        numberOfAnalysed.setBackground(new Color(255, 255, 255));

        experimentDescription2.setText("Analysed Datasets:");

        numberOfLoaded.setEditable(false);
        numberOfLoaded.setBackground(new Color(255, 255, 255));

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(experimentDescription2)
                        .addGap(5, 5, 5)
                        .addComponent(numberOfAnalysed, GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 113, GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(experimentName, GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(experimentDescription1)
                        .addGap(5, 5, 5)
                        .addComponent(numberOfLoaded, GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
        );

        layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {experimentDescription1, experimentDescription2, jLabel1, jLabel2});

        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(experimentName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(numberOfLoaded, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(experimentDescription1))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(numberOfAnalysed, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(experimentDescription2))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextArea experimentDescription;
    private JLabel experimentDescription1;
    private JLabel experimentDescription2;
    private JTextField experimentName;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JScrollPane jScrollPane1;
    private JTextField numberOfAnalysed;
    private JTextField numberOfLoaded;
    // End of variables declaration//GEN-END:variables
}