/*
 * Copyright (C) 2013 theonewithgingahair
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package net.jonathansmith.javadpad.client.threads.singlerecord.gui.user.pane;

import java.awt.Component;

import javax.swing.JLabel;

import net.jonathansmith.javadpad.client.threads.singlerecord.gui.pane.CurrentRecordPane;
import net.jonathansmith.javadpad.api.database.Record;
import net.jonathansmith.javadpad.api.database.records.User;

import org.jdesktop.layout.GroupLayout;

/**
 *
 * @author theonewithgingahair
 */
public class CurrentUserPane extends CurrentRecordPane {
    
    /**
     * Creates new form DisplayExperimentPane
     */
    public CurrentUserPane() {
        initComponents();
    }
    
    @Override
    public void setCurrentData(Record record) {
        if (record == null || !(record instanceof User)) {
            this.dispUsername.setText("");
            this.dispFirstname.setText("");
            this.dispLastname.setText("");
        }
        
        else {
            User user = (User) record;
            this.dispUsername.setText(user.getUsername());
            this.dispFirstname.setText(user.getFirstName());
            this.dispLastname.setText(user.getLastName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        dispUsername = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        dispFirstname = new JLabel();
        dispLastname = new JLabel();

        jLabel1.setText("Username:");

        jLabel3.setText("First Name:");

        jLabel4.setText("Last Name:");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(5, 5, 5)
                .add(layout.createParallelGroup(GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(GroupLayout.TRAILING, false)
                            .add(GroupLayout.LEADING, jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(GroupLayout.LEADING, jLabel3))
                        .add(5, 5, 5)
                        .add(layout.createParallelGroup(GroupLayout.LEADING)
                            .add(dispUsername, GroupLayout.PREFERRED_SIZE, 310, GroupLayout.PREFERRED_SIZE)
                            .add(dispFirstname, GroupLayout.PREFERRED_SIZE, 310, GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(jLabel4)
                        .add(5, 5, 5)
                        .add(dispLastname, GroupLayout.PREFERRED_SIZE, 312, GroupLayout.PREFERRED_SIZE)))
                .add(5, 5, 5))
        );

        layout.linkSize(new Component[] {dispFirstname, dispLastname, dispUsername}, GroupLayout.HORIZONTAL);

        layout.linkSize(new Component[] {jLabel1, jLabel3, jLabel4}, GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(5, 5, 5)
                .add(layout.createParallelGroup(GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(dispUsername))
                .add(5, 5, 5)
                .add(layout.createParallelGroup(GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(dispFirstname))
                .add(5, 5, 5)
                .add(layout.createParallelGroup(GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(dispLastname))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        layout.linkSize(new Component[] {dispFirstname, dispLastname, dispUsername}, GroupLayout.VERTICAL);

        layout.linkSize(new Component[] {jLabel1, jLabel3, jLabel4}, GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel dispFirstname;
    private JLabel dispLastname;
    private JLabel dispUsername;
    private JLabel jLabel1;
    private JLabel jLabel3;
    private JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}