/*
 * Copyright (C) 2013 jonathansmith
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package net.jonathansmith.javadpad.client.threads.data.overview.toolbar;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

import org.jdesktop.layout.GroupLayout;

/**
 *
 * @author jonathansmith
 */
public class DataToolbar extends JPanel {

    public DataToolbar() {
        initComponents();
    }

    public void addDisplayOptionListener(ActionListener listener) {
        this.addData.addActionListener(listener);
        this.loadData.addActionListener(listener);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        addData = new JButton();
        loadData = new JButton();
        analyseData = new JButton();
        viewAnalysed = new JButton();
        back = new JButton();

        setMaximumSize(new Dimension(120, 32767));
        setMinimumSize(new Dimension(120, 0));

        jLabel1.setText("Data Toolbar:");

        addData.setText("Add New Data");

        loadData.setText("View Data");

        analyseData.setText("Analyse Data");

        viewAnalysed.setText("View Analysed");

        back.setText("Back");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(layout.createParallelGroup(GroupLayout.CENTER)
                            .add(viewAnalysed, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
                            .add(analyseData, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(loadData, GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .add(addData, GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .add(back, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)))
                    .add(jLabel1))
                .add(5, 5, 5))
        );

        layout.linkSize(new Component[] {addData, analyseData, back, loadData, viewAnalysed}, GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1)
                .add(5, 5, 5)
                .add(addData)
                .add(5, 5, 5)
                .add(loadData)
                .add(5, 5, 5)
                .add(analyseData)
                .add(5, 5, 5)
                .add(viewAnalysed)
                .add(5, 5, 5)
                .add(back)
                .add(0, 116, Short.MAX_VALUE))
        );

        layout.linkSize(new Component[] {addData, analyseData, back, loadData, viewAnalysed}, GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton addData;
    public JButton analyseData;
    public JButton back;
    private JLabel jLabel1;
    public JButton loadData;
    public JButton viewAnalysed;
    // End of variables declaration//GEN-END:variables
}
